
draw_set_font(font_upgrades)
draw_set_color(c_yellow)
draw_text(140,120,"Cards Received: "+calc_number(cardsRecieved))
draw_set_color(c_white)
draw_text(140,150,"Inheritance x"+calc_number(got_card_inheritance))
draw_text(140,180,"Heartpiece x"+calc_number(got_card_heartpiece))
draw_text(140,210,"Mineshaft x"+calc_number(got_card_mineshaft))
draw_text(140,240,"Farming x"+calc_number(got_card_farming))
draw_text(140,270,"Spike Barrier x"+calc_number(got_card_barrier))
draw_text(140,300,"Magic Orb x"+calc_number(got_card_orb))
draw_text(140,330,"Critical Gold x"+calc_number(got_card_critgold))
draw_text(140,360,"Favored Winds x"+calc_number(got_card_wind))
draw_text(140,390,"Raging Fury x"+calc_number(got_card_rage))
draw_text(140,420,"Shockwave x"+calc_number(got_card_shockwave))
draw_text(140,450,"Supply Drop x"+calc_number(got_card_supplydrop))
draw_text(140,480,"Flying Axes x"+calc_number(got_card_axes))
draw_text(140,510,"Evil Creed x"+calc_number(got_card_evilcreed))
draw_text(140,540,"Mastery x"+calc_number(got_card_mastery))
